services:

  starr-db:
    container_name: starr-db
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_DB: $PG_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - $PG_PORT
    networks:
      - private

  starr-app:
    container_name: starr-app
    restart: always
    build: .
    depends_on:
      - starr-db
    command: poetry run python -m starr
    volumes:
      - ./starr/data/logs:/app/starr/data/logs
    networks:
      - private

networks:
  private:
    external: false

volumes:
  postgres_data:
