[tool.poetry]
name = "starr"
version = "0.1.0"
description = "A dedicated Starboard bot written using Hikari."
authors = ["Jonxslays"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
asyncpg = "^0.25.0"
python-dotenv = "^0.19.2"
hikari-tanjun = "^2.1.4-alpha.1"
uvloop = "^0.16.0"
hikari = {extras = ["speedups"], version = "^2.0.0-alpha.103"}

[tool.poetry.dev-dependencies]
black = "^21.11b1"
mypy = "^0.910"

[tool.black]
line-length = 99

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "asyncpg"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
